### ISSUE TITLE
v2.3.0 some tests not passed

### ISSUE THREAD

**Issue by tim77** [ascii-boxes/boxes#124]
**To Reproduce**  
Build with tests:
```
181 tests executed, 159 successful, 22 failed.
Error in test case: 095_ansi_basic.txt (top: actual; bottom: expected)
Error in test case: 096_ansi_within.txt (top: actual; bottom: expected)
Error in test case: 097_ansi_mixed.txt (top: actual; bottom: expected)
Error in test case: 098_ansi_mixed_indent.txt (top: actual; bottom: expected)
Error in test case: 099_ansi_align_left.txt (top: actual; bottom: expected)
Error in test case: 100_ansi_align_center.txt (top: actual; bottom: expected)
Error in test case: 101_ansi_align_right.txt (top: actual; bottom: expected)
Error in test case: 102_ansi_size.txt (top: actual; bottom: expected)
Error in test case: 103_ansi_pad.txt (top: actual; bottom: expected)
Error in test case: 104_ansi_lolcat.txt (top: actual; bottom: expected)
Error in test case: 105_ansi_lolcat_within_leading_space.txt (top: actual; bottom: expected)
Error in test case: 107_unicode_align_left_lolcat.txt (top: actual; bottom: expected)
Error in test case: 108_unicode_align_center_lolcat.txt (top: actual; bottom: expected)
Error in test case: 109_unicode_align_right_lolcat.txt (top: actual; bottom: expected)
Error in test case: 110_unicode_align_complex_lolcat.txt (top: actual; bottom: expected)
Error in test case: 113_headline_ansi_unicode.txt (top: actual; bottom: expected)
Error in test case: 117_unicode_ansi_mending.txt (top: actual; bottom: expected)
Error in test case: 118_unicode_ansi_align_center.txt (top: actual; bottom: expected)
Error in test case: 119_unicode_ansi_align_right.txt (top: actual; bottom: expected)
Error in test case: 176_utf8_design_list.txt (top: actual; bottom: expected)
Error in test case: 177_utf8_generate_box.txt (top: actual; bottom: expected)
Error in test case: 184_create_box_colored_contents.txt (top: actual; bottom: expected)
```

**Expected behavior**  
Previous versions passed all test.

**Environment (please complete the following information):**  
- *Boxes* version: `v2.3.0`
- Your operating system and architecture: `Fedora Linux 39`; `x86_64` 
- [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=113641323)
- [build.log](https://kojipkgs.fedoraproject.org//work/tasks/1323/113641323/build.log)

**Comment by tsjensen** [comment]
I was afraid this might happen. Looking forward to the cmake build ...

All [CI tests](https://github.com/ascii-boxes/boxes/actions/runs/7941748064) are green, of course (MacOS and Ubuntu Linux), and so were my tests on MinGW32 locally.

So, what may be the difference between our Ubuntu and your Fedora? I'll try to analyze during the weekend. Please share any ideas or hints that you might have!

**Comment by tsjensen** [comment]
Is it a problem with the diff tool? I cannot find any differences between the "actual" and "expected" outputs, even where they are supposed to be different. Can I somehow get the binary data that's being compared (the files that diff is invoked on)?

**Comment by tsjensen** [comment]
Ok, found one root cause in any case: The black-box tests require a color-capable terminal, but `TERM` is set to `vt100`. Can you please try setting it to `xterm-color` or similar ([example](https://github.com/ascii-boxes/boxes/actions/runs/7941748064/workflow#L20))?

**Comment by tim77** [comment]
Can confirm [tests passed](https://src.fedoraproject.org/rpms/boxes/pull-request/1) with `xterm-color`. But this tests still failed on "old" Fedora 38 and EPEL 8, 9. This is not a big issue so we can skip this checks for this branches.

Update built and ready for [testing](https://bodhi.fedoraproject.org/updates/?packages=boxes) for all Fedora and EPEL branched.

However, one test still failed on `s390x` arch [1]. This is totally unnecessary and we could exclude tests for this arch. But if you interesting to investigate and fix this as well let me know. Thanks a lot.

[1]:
```
390x arch:
Error in test case: 150_tag_config_invalid_tags.txt (top: actual; bottom: expected
```

**Comment by tsjensen** [comment]
Glad to hear that! I trust your judgement, of course. If you say we're good, we're good.

I *did* take a quick look at the [build log for epel8](https://kojipkgs.fedoraproject.org//work/tasks/8685/113658685/build.log), and noticed that the black-box tests that failed were those that assumed a system encoding of UTF-8. Unicode capability as such tests out fine, as evidenced by the tests that explicitly specify `-n UTF-8`. In contrast to that, the failing tests assume that the system encoding is set to UTF-8. If you don't mind, I think it's worth a try setting `export LANG=en_US.UTF-8` for the black-box tests.

**Comment by tim77** [comment]
> I think it's worth a try setting export LANG=en_US.UTF-8 for the black-box tests.

[This](https://src.fedoraproject.org/rpms/boxes/c/4629d8837fc5a5b6d1867ae3c435f935fabb130a?branch=rawhide) fixed tests for EL 8. Thanks!

**Comment by tsjensen** [comment]
Thank you for taking care of boxes, and for being so fast! 🏎️⭐
