### ISSUE TITLE
Contact info for artist Joan Stark

### ISSUE THREAD

**Issue by mdebusk** [ascii-boxes/boxes#126]
I was looking through `usr/share/boxes` just now and noticed several references to a GeoCities page by ascii artist Joan Stark. As GeoCities no longer exists, I went looking for her and found she has (at the least) reclaimed her privacy.

Her site is archived, however, at [:joan stark's ASCII Art Gallery:](https://oldcompcz.github.io/jgs/joan_stark/). There are reasonable arguments both for and against updating the references. I just wanted to suggest doing so.

**Comment by tsjensen** [comment]
Great find! And in her "guidelines on using my ASCII art", it says:

> Q #1:  Can I use this ASCII Art?
>
> Yes, but I do have a few conditions.  They are pretty simple to follow.
> 1. please leave my initials (`jgs`) on the pictures
> 2. for personal use only  (commercial readers keep reading)
> 3. optional conditions :
>    a. link to this website  (http://www.ascii-art.com)
>    b. tell a friend about this site!
>    c. send a postcard via snail mail to me and my family
>    d. consider making a donation

So, as we are an open-source, non-commercial project, we are good by having the `jgs` initials on her box designs.

**Comment by tsjensen** [comment]
The links are "optional". We still reference the website in multiple places, but the links have gone cold:

- <http://www.geocities.com/SoHo/7373/> - the original site, referenced by us currently, cold
- <http://www.ascii-art.com> - newer address, references by guidelines above, cold
- <https://oldcompcz.github.io/jgs/joan_stark/> - unofficial copy by a JGS fan, works

I notice that Joan Stark did not specify a license for the website, only for the artwork.
Copyright law says that this means we may use the artwork, but not the website itself.
Purely from a legal point of view, the "unofficial copy" site is violating copyright ...

IANAL, but this would kind of keep me from linking to it as a means of improvement.
I would lean towards not changing anything right now. The link was fine at the time of
creation. Websites do not live forever. And anyway, we are using the link only as
decoration in the samples. If it somehow became a problem, we could just remove it
entirely.

**Comment by mdebusk** [comment]
Looks like this issue is worth closing, then. :)
