### ISSUE TITLE
Possible JavaScript port?

### ISSUE THREAD

**Issue by MarketingPip** [ascii-boxes/boxes#128]
Would it be possible to get this as a port to JavaScript or directly compiled to JavaScript so we can use it as ESM module?

**Comment by tsjensen** [comment]
You mean, theoretically? Sure! It would be pretty much the same effort as the original program (maybe a little more). But if you manage to have it pass the end-to-end test suite, I'll host it in the ascii-boxes group. 😄

**Comment by MarketingPip** [comment]
@tsjensen - no I mean like compile this directly to wasm etc.... So we can grab it via JS library or (re write from scratch in JS - other route to do this)

**Comment by tsjensen** [comment]
I see. Still. Sorry!

This question has become something of an FAQ, so I've added a longer answer there: <https://boxes.thomasjensen.com/faq.html#q8>
