### ISSUE TITLE
Question: is this use-case possible with boxes [+ other tools]?

### ISSUE THREAD

**Issue by balaclava-guy** [ascii-boxes/boxes#129]
Hello,

I want to create simple menus (example image below) that are overlayed on top of e.g. terminal ANSI art, but without repeating the background image (i.e. the menu extends beyond the bottom of the image).

I know boxes isn't really designed for this use-case, but wondered if this as achieveable by piping through other tools? I am not super familiar with other tools in this space so thought this might be a good place to ask.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/0eb9f212-5975-4750-957a-1dcc73a313ba">

**Comment by tsjensen** [comment]
Since boxes v2.3.0, you can indeed create boxes like the one shown, even including the pink background color. I would like to add a nice ANSI art box to the official config file, but thus far haven't really found one.

It looks like you also need a tool for creating the tree structure, like the `tree` command in Windows.

**Comment by balaclava-guy** [comment]
> Since boxes v2.3.0, you can indeed create boxes like the one shown, even including the pink background color. I would like to add a nice ANSI art box to the official config file, but thus far haven't really found one.
> 
> It looks like you also need a tool for creating the tree structure, like the `tree` command in Windows.

Thanks! Actually I am looking more for something that will position the box in just the right place over the ANSI background image. The background image is not a repeatable pattern, as you can see, so I just want the `boxes` output to extend down past the end of the image (depending on the size of the output. e.g. `tree` or whatever else goes in).

I know this isnt really in scope for `boxes`, but I'm thinking maybe combined with another terminal tool. I've tried `tput` but not had much luck?

**Comment by tsjensen** [comment]
It's not a problem that the background isn't repeatable. You can make use of the [grid system](https://boxes.thomasjensen.com/config-general.html) and use NW and WNW shapes, and maybe an elastic W shape. The box would be two lines longer than shown in your example, but otherwise fine! 🙂
