### ISSUE TITLE
Create boxes-config from individual design definitions only on build

### ISSUE THREAD

**Issue by MichaelTiernan** [ascii-boxes/boxes#14]
Have you considered breaking the boxes-config file down into consituent parts with a makefile (or such) to bring them together?

**Comment by MichaelTiernan** [comment]
Okay, so I decided to create an example.
I've stored it as a tar file:
 https://dl.dropboxusercontent.com/u/27834209/suggested.tar.gz

**Comment by tsjensen** [comment]
This would save people some scrolling, that's true. On the other hand, you could not easily copy the current version of the config file from GitHub and use it right away. Not sure if we would want that.

There is issue #5 however, which is an enhancement request to use more that one config file when running boxes. This way, one could keep the *official* config file unchanged, and put custom designs in a user-specific file. Also handy for people who don't have the access rights to modify the central file.

**Comment by MichaelTiernan** [comment]
I'm more of the idea that the boxes-config file is a concatenation of the contents of the "config" directory so that it's easier to track changes to individual format definitions easier.
The *distributed* version, that is installed is the all-in-one boxes-config file.

**Comment by tsjensen** [comment]
Yes, I think I get you. The example you provided is quite clear. So I understand *what* you want to do, but I don't understand the *why*. We would sacrifice the ability to pull the latest box designs into an existing boxes installation (even without the access rights to update the installation). So, what would we gain?

**Comment by tsjensen** [comment]
I'm closing this because the discussion seems to have stalled. We can reopen this anytime.
