### ISSUE TITLE
boxes RPM doesn't exist for Fedora EPEL 7

### ISSUE THREAD

**Issue by seanscottking** [ascii-boxes/boxes#29]
Hey, first of all thank you for your `boxes` project. I use it all the time with CentOS 6 via EPEL.

I recently started using CentOS 7, but EPEL 7 does not have a `boxes` package available yet. See [this link](https://apps.fedoraproject.org/packages/boxes/overview/).

I'm not a developer/EPEL expert, just a lowly sysadmin type of person, but is there anything I can do to help?

Let me know if this is the wrong place to bring it up and I'll take the issue elsewhere.

**Comment by tsjensen** [comment]
Glad to hear you like boxes!
The Fedora packaging process is handled downstream, so you would have to ask Jakub (the maintainer of the package) to do a release for EPEL 7.

**Comment by seanscottking** [comment]
OK great, thanks @tsjensen. His github username is @jhrozek, so maybe I can get his attention here. If he doesn't answer I'll email him directly.

**Comment by jhrozek** [comment]
Please open a bug against boxes at bugzilla.redhat.com, I don't really have an isue with adding boxes to EPEL-7, but I would prefer to track that in a distribution tracker rather than github.

**Comment by seanscottking** [comment]
Thanks @jhrozek, I did as you suggested: https://bugzilla.redhat.com/show_bug.cgi?id=1350500

**Comment by jhrozek** [comment]
And I built the package already:)

**Comment by tsjensen** [comment]
Cool, thank you @jhrozek! :+1:
