### ISSUE TITLE
Create vim syntax file for boxes config files

### ISSUE THREAD

**Issue by tsjensen** [ascii-boxes/boxes#4]
Create vim syntax file for boxes config files.
My current try (https://github.com/tsjensen/boxes/blob/master/boxes.vim) works fine except for the problems mentioned at the top of the file.
Forecast: I'm stuck, but I'd like to have it
![boxes-syntax](https://cloud.githubusercontent.com/assets/7677131/4068023/3dae6322-2e34-11e4-9bc3-a4bf2f8fe19c.gif)

**Comment by AriSweedler** [comment]
Is this completed? The problem stated in the file is currently:

`does not allow correct colorization of strings following a DELIM`. But that seems to work fine. Am I missing something?

**Comment by tsjensen** [comment]
Hi! After more than 15 years, this was a good opportunity to try it out once more. 😄  
The syntax file actually seems to be in good enough shape that I would say today that it's completed. This may be because Vim has evolved a lot during that time, but who knows, maybe my standards were higher back then.

I just tested it again on the official boxes config file, and it worked ok. There are obviously some problems with handling escapes in strings, and when the `delimiter` statement changes the string delimiter to something other than double quote (`"`), those strings will not be highlighted correctly. I'll create separate issues for those problems.

**Comment by tsjensen** [comment]
Opened #63 and #64 in the hopes that someone can improve the syntax file.

Otherwise, I think it's still good enough to use in the wild. Updated website to tell people about it.

**Comment by tsjensen** [comment]
@AriSweedler I saw that you are a Vim expert - it would be fantastic if you could help with this!

**Comment by AriSweedler** [comment]
I'm no expert, I'm definitely interested though! I was actually looking for a project to motivate me to study `:help syntax`, and this seems perfect for that. I didn't understand the problem until you made those 2 new issues (thank you for making them very clear and understandable). I look forward to trying to solve this!
