### ISSUE TITLE
Word/line wrap based on size variable

### ISSUE THREAD

**Issue by J4bber** [ascii-boxes/boxes#42]
Would like to see it automatically word-wrap on long lines based on the -s setting.

Example:

1234567890

boxes -s 7

```
!!!!!!!
!12345!
!67890!
!!!!!!!
```

**Comment by tsjensen** [comment]
Interesting idea! I'm adding it to the list.
However, just as a note, we would depend on someone to contribute this, as *boxes* is currently in maintenance mode only.

**Comment by tsjensen** [comment]
This is issue 42! 😄

**Comment by J4bber** [comment]
Hehe

**Comment by tsjensen** [comment]
Just a thought: Would it help to use the `fmt` command from the GNU coreutils?
`echo 12345 67890 09876 54321 | fmt -w 5 | boxes -d stone`
```
+-------+
| 12345 |
| 67890 |
| 09876 |
| 54321 |
+-------+
```
It doesn't split words, though. But I'm sure there's a tool for that, too. 😇

**Comment by tsjensen** [comment]
Ah, there is `fold` for splitting words, as in `echo 12345678900987654321 | fold -w5 | boxes -d stone`.

Then I think we can close this issue. Please let me know if I've missed anything.
