### ISSUE TITLE
Boxes could handle escape sequences (especially for colors and box characters) better

### ISSUE THREAD

**Issue by jrcharney** [ascii-boxes/boxes#49]
[My submitted answer on StackExchange](https://unix.stackexchange.com/questions/70615/bash-script-echo-output-in-box/464432#464432) for someone who wanted color text and color box borders could have been better.

Apparently, `boxes` does not handle colored text very well.

```
 printf "$(tput setaf 4)Love Unix & Linux$(tput sgr 0)" | boxes -d stone -p a2v1 
+---------------------------------+
|                                 |
|  Love Unix & Linux  |
|                                 |
+---------------------------------+
```

So what caused this fail? `cat -A` explains it all.

```
 printf "$(tput setaf 4)Love Unix & Linux$(tput sgr 0)" | boxes -d stone -p a2v1 | cat -A
+---------------------------------+$
|                                 |$
|  ^[[34mLove Unix & Linux^[(B^[[0m  |$
|                                 |$
+---------------------------------+$
```

`boxes` will read the escape characters and include them as the length of the text.  This should not happen.

And don't get me started on what it looks like if you pipe `lolcat -f` between the `printf` or `echo` statement and the `boxes` command.

This brings up what happens if you try to do the same with box characters, which I had hoped to include as part of my own box designs. However if this is happening

```
printf "▁▂▃▄▅▆▇▇▆▅▄▃▂▁" | boxes -d stone -p a2v1
+----------------------------------------------+
|                                              |
|  ▁▂▃▄▅▆▇▇▆▅▄▃▂▁  |
|                                              |
+----------------------------------------------+
```
because `cat -A` says this is how it is being interpreted

```
 printf "▁▂▃▄▅▆▇▇▆▅▄▃▂▁" | boxes -d stone -p a2v1 | cat -A
+----------------------------------------------+$
|                                              |$
|  M-bM-^VM-^AM-bM-^VM-^BM-bM-^VM-^CM-bM-^VM-^DM-bM-^VM-^EM-bM-^VM-^FM-bM-^VM-^GM-bM-^VM-^GM-bM-^VM-^FM-bM-^VM-^EM-bM-^VM-^DM-bM-^VM-^CM-bM-^VM-^BM-bM-^VM-^A  |$
|                                              |$
+----------------------------------------------+$
```

Then `boxes` still needs work.

**Comment by tsjensen** [comment]
First of all, thank you for pointing others to *boxes*, we appreciate that!

About your issue, you are absolutely correct! It's in fact our issue #1, easily the single most important feature request for *boxes*. UTF-8 is just the most common occurrence of the fact that one character may be represented by multiple bytes. In your case, it is also color information which modifies the appearance of a character (its color).

In addition to that, we would also like to have UTF-8 in box designs, which would enable still more interesting designs.

Unfortunately, as you can read in #1, this would be a major extension which I cannot currently implement myself. If you (or anybody) were to contribute it, I would be happy to assist as best I can, of course.

**Comment by tsjensen** [comment]
One down! Handling of escape sequences has been added in #68 by @residualmind. 😊

**Comment by tsjensen** [comment]
#1 was implemented (finally!). The only part of *boxes* that isn't MBCS enabled yet is the config file, which we are tracking in #72.

So I'm closing this in favor of #72. I hope that's ok! Let me know if I've missed anything.
