### ISSUE TITLE
boxes-1.2 variable settings in Win10

### ISSUE THREAD

**Issue by rapolive** [ascii-boxes/boxes#51]
When trying to run boxes from prompt/cmd that returns an error:
boxes: Couldn't open config file 'C:\Program Files\boxes-1.2' for input (taken from $BOXES).
but boxes.cfg is inside the mentioned directory as above.

I've already pre-set the path variable as well, like:
setx /M path "%path%;C:\Program Files\boxes-1.2"

Any suggestion, please.
regards,
Raphael

**Comment by tsjensen** [comment]
`BOXES` points to the *file*, not the directory containing the file.
Try setting it to *C:\Program Files\boxes-1.2\boxes.cfg*, or just unset the environment variable, in which case the file must be located next to the executable.

**Comment by rapolive** [comment]
Hi Thomas, thanks for replying.
I can see another variable named BOXES under HKEY_CURRENT_USER\Environment thus I could add boxes.cfg which just last for the first time until I boot the system... Still investigating cause that worked inside the prompt by running:
echo "test" |boxes

regards
Raphael

**Comment by rapolive** [comment]
Hi, could solve that...
I'm touching the system variable:
BOXES=C:\Program Files\boxes-1.2\boxes.cfg
PATH=%Path%;C:\Program Files\boxes-1.2 << this one cannot have the .cfg file otherwise won't work.
Notepad++ has some strange use, it takes just Plugin\NppExec\Execute to work the script but not in the Macro menu...
Anyway I can always take hand the shortcut F6 and change the parameters for boxes.

Thanks
Raphael

**Comment by tsjensen** [comment]
Ok, great! Then I understand the issue is solved?

**Comment by rapolive** [comment]
Yes that's solved... boxes works fine!
greetings
