### ISSUE TITLE
incorrect Chinese alignment 

### ISSUE THREAD

**Issue by YiZhangCUG** [ascii-boxes/boxes#53]
If the input has Chinese words, the alignment is not right. Looks like this:
/***************************************************/
/* This is a test string. 这是一个测试段落 */
/***************************************************/

**Comment by tsjensen** [comment]
Yup, *boxes* is still on single-byte character sets.

This is actually our most requested feature, but also a lot of work to change.

I'm closing this in favor of #1 and #49, which mostly describe the problem in detail.

**Comment by tsjensen** [comment]
Actually, looking at your example, I noticed that you use a proportional font.  
This is unlikely to work with boxes, which assumes a monospace font (like Courier or Consolas). You'd still need a monospace font, even if the MBCS support was implemented.

**Comment by tsjensen** [comment]
FYI, #1 was implemented (finally!). It will take some time to update the distribution packages, but starting with v2.0.0, this will work. 😊
