### ISSUE TITLE
Better if the error prompt is more friendly

### ISSUE THREAD

**Issue by kkew3** [ascii-boxes/boxes#54]
Before I carefully went through the manual, I attempted to set the width only by `boxes -s 70x`. Apparently it would fail, but with prompt:

```
boxes: box size: Interrupted system call, '70x'
```

I believe it might be better to show a more friendly prompt when there's parsing error with option string, with something like "boxes: box size: illegal option string", for example. Thanks!

`boxes` version: `1.2`.

**Comment by tsjensen** [comment]
Dang, this works for me! &rarr; `echo foo | boxes -s 70x`:
```
/********************************************************************/
/* foo                                                              */
/********************************************************************/
```
I agree it's kind of a gray area if this should be possible, but you deserve a better error message! 😉 

What system are you on? Are you using a particular binary? How did you install it?

**Comment by kkew3** [comment]
Thanks for your reply. I'm on `mac OS Majove Version 10.14.1 (18B75)`. I installed by `brew install boxes`.

**Comment by tsjensen** [comment]
Is it 32bit or 64bit?

(I don't have direct access to a Mac, but I'll try to get a colleague to try your case. It may take some time though, as everybody is on Christmas vacation currently.)

**Comment by kkew3** [comment]
It's 64bit.

Thanks. No problem. It should be written as `-s 70` anyway, as per the manual.

**Comment by tsjensen** [comment]
It turned out I didn't get access to a Mac, but I believe I fixed it by looking closely at the code.  
Do give it a try. I feel confident enough to close this. Let me know if it turned out ok. 😉 
Be sure to test using *boxes* 1.3.

**Comment by kkew3** [comment]
Thanks! The latest version of `boxes` on `brew` is 1.2. I'll try it out when 1.3 is available.

**Comment by kkew3** [comment]
It works perfectly now. Thanks!

```bash
prompt> echo hello | boxes -s 70x
boxes: invalid box size specification -- 70x
```
