### ISSUE TITLE
Outfile not recognized when -r is specified (box removal)

### ISSUE THREAD

**Issue by pidgeon777** [ascii-boxes/boxes#55]
This is what I actually do into Notepad++ to generate a box around a text selection, according to the docs:

`boxes.exe -d stone -s 80 -ac "$(ascfile)" "$(tempfile)"`

By doing so, it works.

But, if I want to remove the box through:

`boxes.exe -r -d stone "$(ascfile)" "$(tempfile)"`

then the resulting output is sent to the stdout (shown in NppExec console), and not to the `$(tempfile)` file, thus the originally selected text is replaced with an empty string.

I'm using boxes version 1.2.

**Comment by tsjensen** [comment]
Good catch! While this is being fixed, you can use the following workaround:

`cmd /c boxes -r -d stone "$(ascfile)" > "$(tempfile)"`

The NppExec manual actually says one should do it like this, but according to the *boxes* docs, what you did should have worked, too.

**Comment by tsjensen** [comment]
I updated the [docs](http://boxes.thomasjensen.com/docs/install.html#notepadplusplus) to avoid further confusion.  
Fixing this in the code will take much longer, but we should be good for now. 😉

**Comment by pidgeon777** [comment]
Thank you for the prompt reply, your proposed solution is actually working good. I also think it can be considered a good workaround until a solution to the bug will be found.

**Comment by tsjensen** [comment]
Fixed in master. This will go out with the next release, but be patient as that may take some time.

**Comment by pidgeon777** [comment]
No problem, I will wait, then.

**Comment by tsjensen** [comment]
Released as 1.3
