### ISSUE TITLE
Indentation isn't maintained when processing a text selection with Notepad++

### ISSUE THREAD

**Issue by pidgeon777** [ascii-boxes/boxes#56]
I'm not able to maintain the original text indentation when processing the selection through Boxes with Notepad++.

A demonstration follows below. At first, the selected text is indented with tabs, but when I process the selection through `"$(boxes_p)" -i box -t 4 -d c-cmt2 "$(ascfile)" "$(tempfile)"`, then the tab indentation gets lost (you can notice that by looking at the cursor's movements):

![iwbrt29eyd](https://user-images.githubusercontent.com/13739892/52646070-6300e380-2ee2-11e9-8a9e-9e69c858ac5e.gif)

The sample text I'm trying to enclose with Boxes:

````
	Basedsad
	as as dsa dsa readdirsad stackavail asd 
	as das das
	
			dfsdf
			sadfsdf
			sdfsdf
			
			   asdasd
			   asdasdff
			   f

  asd
    as fas 
	fas 
as
````
I'm using boxes version 1.2.

**Comment by tsjensen** [comment]
Try `-t 4k` or `-t 4u` instead of just `-t4`. (Explanation [here](http://boxes.thomasjensen.com/docs/boxes-man-1.html) - scroll down a bit for `-t`.)

**Comment by pidgeon777** [comment]
Thank you, I tried with both `-t 4k` and `-t 4u`, both seem to keep the leading tabs as expected.

But now another problem arises, when I try to process those lines with boxes, then tabs are replaced with spaces. Example, before boxes applied:

![image](https://user-images.githubusercontent.com/13739892/52729743-0ffa5f80-2fba-11e9-9ce5-834eb7202e8c.png)

After boxes applied:

![image](https://user-images.githubusercontent.com/13739892/52729759-17ba0400-2fba-11e9-83cd-e5227445cdd6.png)

Is there any way to keep the tabs even of the commented code ("enclosed" with boxes)?

**Comment by tsjensen** [comment]
From the docs:

> … In the box content, tabs are always converted into spaces.

The reason for this is that we need to handle the text inside the box precisely, so as to accommodate the shape sizes of the chosen box design, plus padding, text alignment, and so forth. So, retaining some tabs would again only work for some specific box designs, or even depend on the amount of indentation to the left of the box.

**Comment by pidgeon777** [comment]
Thank you. Regarding the box designs which would allow maintaining the tabs, is there any list available?

Particularly, I suppose you're referring to some "simple" schemes like the followings:

````
// XXX
// XXX
// XXX
````

````
/*
   XXX
   XXX
   XXX
*/
````

Well, when using Boxes to comment out some code I think it could be nice to maintain the tabs.

**Comment by tsjensen** [comment]
No list. Like I explained in [#57](https://github.com/ascii-boxes/boxes/issues/57#issuecomment-463358822), we can't have features that work only for some box designs. All features must always work for all box designs. Maintaining tabs inside the box is impossible except in carefully constructed cases.

**Comment by pidgeon777** [comment]
Understood. Hopefully one day a specific tool for that task will be released, it would be nice to have a special Boxes edition for commenting/uncommenting code with indentation preservation.
