### ISSUE TITLE
Ability to integrate input text into the box frame

### ISSUE THREAD

**Issue by tsjensen** [ascii-boxes/boxes#6]
Ability to integrate input text into the box frame (submitted by Tobias Buchal on Thu, 13 Jan 2000)

Orginal Text:

```
    file:line
    test text text
    test text text
```

Desired Output:

```
    |---(file:line)------     <-- this line must currently be done manually
    |test text text
    |test text text
    |--------------------
```

While this feature is not implemented, the effect must be achieved by using editor mappings.

**Comment by antofthy** [comment]
perhaps a 'title' or 'frame text' type option?

**Comment by tsjensen** [comment]
Perhaps! 😉 Configuring it would actually be quite easy, but what makes this tricky are the consequences:
- Would the dynamic text be limited to one shape?
- If not, how would you specify the way it spans shapes?
- What is the impact on elasticity?
- Can this be done anywhere in the box, or just in the top side?
- What do you do with the output of `-l -d`, where a minimum box size is printed?
- ... and probably some more questions

It's not impossible, but not as simple as one might think just looking at the requirement. 😊

**Comment by tsjensen** [comment]
Going through the issues, this seems like it would cause too much trouble. Also, it didn't receive much attention.

Closing as 'won't do'.
