### ISSUE TITLE
Vim syntax file: Setting `iskeyword` globally in vim script breaks other plugins

### ISSUE THREAD

**Issue by tartansandal** [ascii-boxes/boxes#66]
The boxes.vim has a global setting that effects many other filetype plugins:

```viml
" Set the keyword characters
set iskeyword=a-z,A-Z
```

The default value for this option: is `@,48-57,_,192-255`.

Most plugins add or remove specific characters in a buffer local fashion. Completely resetting the global value has unintended consequences, such as, '*' command no longer works as expected.

**Comment by tsjensen** [comment]
Thanks for catching this! 👍

What do you suggest that we change?

**Comment by tartansandal** [comment]
To be honest, I'm not 100% sure. I only found this while tracking down some odd behaviour.

Just had a look at the files in my distributions Vim.  All the syntax and ftplugin files use

```
setlocal iskeywork=...
```
That makes more sense to me :smile:

**Comment by tartansandal** [comment]
Did some more digging. Looks like the Fedora/RedHat packagers have been installing this script as a global `plugin` rather than a `syntax` file. Hence, being loaded even though I was not editing `.boxes` files.   Going to have to dig up my bugzilla password again ;-)

**Comment by tsjensen** [comment]
Thanks for the analysis. It seems you have found to root cause.

Is there anything I can do to help?

**Comment by tartansandal** [comment]
Using `set iskeyword` rather than `setlocal iskeyword` is *technically* incorrect. You may want to change that, since it may still effect *some* users, even if the correct installation paths are used.

I've raise a bug at https://bugzilla.redhat.com/show_bug.cgi?id=1796282 to get the installation paths fixed. Not sure if the maintainer understands the issue yet though.

**Comment by tsjensen** [comment]
I've updated the syntax file, so as far as I understand it, this issue should be resolved.

Thanks @tartansandal for making the package maintainer aware of his path problem.  
And Artem, if you're reading this, thank you for taking care of boxes out there!
