### ISSUE TITLE
Add support for XDG Base Directory Specification

### ISSUE THREAD

**Issue by mdebusk** [ascii-boxes/boxes#69]
**Boxes** currently looks in `$HOME` for its user configuration file. This practice clutters `$HOME` with countless dotfiles and makes organization difficult. The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) helps to solve this problem by putting a program-specific directory under (usually) `$HOME/.config`. I would love to see **boxes** support this.

I am currently running **boxes** version 1.2 on Ubuntu 18.04.4 LTS.

**Comment by tsjensen** [comment]
Thanks for sharing this idea! It seems to me to be a more generalized version of #5.

The XDG Spec has some weird requirements, such as having to detect when a user logs on, and creating a directory at that time. We would probably not be able to to that. But we could at least know about the environment variables and look for config files in the right places.

I think in addition to precedence etc. it is necessary to be able to read more than 1 config file. In that way, we could have the config that is shipped with *boxes*, and user-specific files which add to that.

**Comment by mdebusk** [comment]
> Thanks for sharing this idea! It seems to me to be a more generalized version of #5.

I must have misunderstood #5. I thought it was asking to be able to choose which config file to use, e.g., specifying it on the command line.

> we could at least know about the environment variables and look for config files in the right places.

That's all I was really asking for.

> I think in addition to precedence etc. it is necessary to be able to read more than 1 config file. In that way, we could have the config that is shipped with _boxes_, and user-specific files which add to that.

Yes. I was thinking I might want to edit a couple of the styles to include vim's folding markers. That's not something most people would want, I believe, but it'd save me a couple of minutes a year. :D

**Comment by tsjensen** [comment]
> I must have misunderstood #5. I thought it was asking to be able to choose which config file to use, e.g., specifying it on the command line.

Well, never mind! (We have the [-f](https://boxes.thomasjensen.com/docs/boxes-man-1.html) option already.)

I'll keep both issues open until we have this sorted out. Please feel free to contribute! These days, *boxes* evolves mainly through contributions.

**Comment by mdebusk** [comment]
> Please feel free to contribute! These days, _boxes_ evolves mainly through contributions.

If I were at all competent with programming, I would. This looks like a fun project.

**Comment by tsjensen** [comment]
I'm actually looking at this feature request again. XDG ist somewhat overengineered, it seems, and there is [discussion](https://www.reddit.com/r/archlinux/comments/k65855/rethinking_the_xdg_base_directory_specification/) on the best degree to which to implement it. But it also seems to me that we *should* implement at least some of it.

My current take is this:

- Support looking for `$XDG_CONFIG_HOME/boxes`
- Support looking for `~/.config/boxes`
- Do **not** support `$XDG_CONFIG_DIRS`.

I would throw in support for more file names, so we'd look for `boxes`, `.boxes`, and `boxes-config`.

What do you think? Would this be sufficient?

**Comment by tsjensen** [comment]
I'm actually looking at this feature request again. XDG ist somewhat overengineered and not very precise, it seems, and there is [discussion](https://www.reddit.com/r/archlinux/comments/k65855/rethinking_the_xdg_base_directory_specification/) on the best degree to which to implement it. But it also seems to me that we *should* implement at least some of it.

My current take is this:

| Precedence | Path | Source | Type | Comment |
|-------------|------|:-------|------|-----------|
| 1 | cmd line `-f` | boxes&nbsp;legacy | file(!) or dir | should be a file, but could now also be a dir |
| 2 | `$BOXES` | boxes&nbsp;legacy | file(!) or dir | should be a file, but could now also be a dir |
| 3 | `$HOME` | boxes&nbsp;legacy | dir | &nbsp; |
| 4 | `$XDG_CONFIG_HOME/boxes` | XDG | dir | &nbsp; |
| 5 | `$HOME/.config/boxes` | XDG | dir | &nbsp; |
| 6 | `/etc/xdg/boxes` | XDG | dir | &nbsp; |
| 7 | the hard-coded system-wide config file mentioned in man page | boxes legacy | file | &nbsp; |
| 8 | `/usr/local/share/boxes` | XDG | dir | if it were a file, then only as per (7) |
| 9 | `/usr/share/boxes` | XDG | dir | if it were a file, then only as per (7) |

The XDG environment variable `$XDG_CONFIG_DIRS` would **not** be supported. However, its default value would be supported as (8) and (9) above.

Whenever the type is *dir* in the tabel above, in that directory we' look for these files, in this order:

1. `.boxes`
2. `boxes-config`
3. `boxes`

As soon as the first valid file is found, we use that and stop the search.

What do you think? Would this be sufficient?

**Comment by mdebusk** [comment]
I think this would be excellent.

**Comment by tsjensen** [comment]
Ok, I am using this comment to document the new behavior until it is done. So this comment may change a few times.

Prec. | Path | Source | Type | Comment | *nix | Win
-- | -- | -- | -- | -- |:--:|:--:
1 | cmd line -f | boxes legacy | file(!) or dir | should be a file, but could now also be a dir | x | x
2 | $BOXES | boxes legacy | file(!) or dir | should be a file, but could now also be a dir | x | x
3 | `.` | new&nbsp;behavior | dir | &nbsp; | x | x
4 | $HOME | boxes legacy | dir | &nbsp; | x |
5 | $XDG_CONFIG_HOME/boxes | XDG | dir | &nbsp; | x |
6 | $HOME/.config/boxes | XDG | dir | &nbsp; | x |
7 | /etc/xdg/boxes | XDG | dir | &nbsp; | x |
8 | the hard-coded system-wide config file mentioned in man page | boxes legacy | file | &nbsp; | x | x
9 | /usr/local/share/boxes | XDG | dir | if it were a file, then only as per (7) | x |
10 | /usr/share/boxes | XDG | dir | if it were a file, then only as per (7) | x |
11 | EXE path, with `.cfg` extension | boxes legacy | file | .cfg file located next to .exe file | &nbsp; | x

The XDG environment variable `$XDG_CONFIG_DIRS` will **not** be supported. However, its default value would be supported as (8) and (9) above.

Whenever the type is *dir* in the table above, in that directory we'll look for these files, in this order:

1. `.boxes`
2. `box-designs`
3. `boxes-config`
4. `boxes`

As soon as the first valid file is found, we use that and stop the search.

**Comment by tsjensen** [comment]
Done. This will be in the v2.1.0 release.

**Comment by tsjensen** [comment]
By the way, code for the already completed new features is collected on the [rc_2.1.0](https://github.com/ascii-boxes/boxes/tree/rc_2.1.0) branch, in case you want to have a look.

**Comment by mdebusk** [comment]
On 2021-03-19 16:04, Thomas Jensen wrote:

> By the way, code for the already completed new features is collected
> on the rc_2.1.0 [1] branch, in case you want to have a look.

Thanks, I'll do that. :)

-- 
Home: http://nlphilia.com * Blog: http://nlphilia.net
Registered Linux User #450983 * Ubuntu Counter Project #10548
