### ISSUE TITLE
Error in test case: 114_headline_ansi_unicode_remove.txt

### ISSUE THREAD

**Issue by tim77** [ascii-boxes/boxes#73]
Hello. There very minor issue in new version during tests. In v2.0.0 all tests passed except this one:

```
Error in test case: 114_headline_ansi_unicode_remove.txt (top: actual; bottom: expected)
```

**To Reproduce**  
1. Compile _boxes_ from sources.
2. Run `make test`.

**Expected behavior**  
All tests passed.

**Environment (please complete the following information):**  
- *Boxes* v.2.0.0
- Fedora 33

**Comment by tsjensen** [comment]
I'll look at it asap. Hopefully, I can use my Fedora commands from #67!

**Comment by tsjensen** [comment]
Alright, checked it out. At first, I stumbled upon a few errors which came from me having copied the files from a Windows machine. The test runner still doesn't always grok Windows line breaks. This affected 4 test cases here, not including 114.

After fixing the line breaks, all was fine!

```
...
121 tests executed, 121 successful, 0 failed.
[root@dcdf02dfccd0 boxes]# uname -a
Linux dcdf02dfccd0 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@dcdf02dfccd0 boxes]# cat /etc/fedora-release
Fedora release 33 (Thirty Three)
```
Can you check if maybe it's just line breaks for you, too? Else we'd need more info, like the full error message, or even debug output.
You can activate debug output by uncommenting the [flag in boxes.h.in](https://github.com/ascii-boxes/boxes/blob/f4f14cdc61cf70fd0d75aa34976fe90f3dfe79a5/src/boxes.h.in#L28).

**Comment by tim77** [comment]
Here is what happening in 114:

```
Running test case: 114_headline_ansi_unicode_remove.txt
    Invoking: boxes -d headline -p l3r2 -r
1c1
<    [38;5;44mf[38;5;49mo[38;5;48mo[38;5;83m [38;5;118m???[38;5;154m [38;5;184mb[38;5;214ma[38;5;208mr
---
>    [38;5;44mf[38;5;49mo[38;5;48mo[38;5;83m [38;5;118m海[38;5;154m [38;5;184mb[38;5;214ma[38;5;208mr
```

But actually in my terminal this look like this, nice and colorful:

```
<    foo ??? bar
---
>    foo 海 bar
```

- [Full build log](https://kojipkgs.fedoraproject.org//work/tasks/3463/62263463/build.log)
- SRPM - https://kojipkgs.fedoraproject.org//work/tasks/3458/62263458/boxes-2.0.0-1.fc33.src.rpm

**Comment by tsjensen** [comment]
Thanks for providing the source RPM. I could reproduce the problem.

It seems there was really a mistake in the test case, which would make it break when the system the test was executed on was not configured for UTF-8. It seems the RPM building environment is one such system.

I think I fixed it - can you please try again? 🤞

**Comment by tim77** [comment]
Tested with version from master and all tests passed now. :+1:  :smiley:
