### ISSUE TITLE
How to select "default" box?

### ISSUE THREAD

**Issue by mathomp4** [ascii-boxes/boxes#75]
I'm wondering if there is a way to select the default box generated when you just run `boxes`?  I know the C box is the one that "wins" per the [webpage](https://boxes.thomasjensen.com/examples.html), but I mainly do Fortran programming, so I'd like that to be the default.

Is there a "tag" maybe I can add to `boxes-config`? Say `tag default`?

**Comment by tsjensen** [comment]
The default box design is simply the first box design in the file.

So you could move up the Fortran box to the top and it should be the new default.

**Comment by mathomp4** [comment]
> The default box design is simply the first box design in the file.
> 
> So you could move up the Fortran box to the top and it should be the new default.

Ah okay. Though I guess if I sync up to the repo's `boxes-config` in a new release it will overwrite. Hmm...

**Comment by tsjensen** [comment]
> I guess if I sync up to the repo's boxes-config in a new release it will overwrite.

True, but so would any other thing you put in the config file, like `tag default`. 😉

**Comment by mathomp4** [comment]
@tsjensen Oh. Yeah. Hmm. Maybe a `.boxesrc` along with `.boxes`? Or maybe a `BOXES_DEFAULT_BOX` environment variable.

So many boxes... 😄

**Comment by tsjensen** [comment]
Naa, that's too complicated. Instead, write a small script that (pseudocode):
1. curl https://raw.githubusercontent.com/ascii-boxes/boxes/master/boxes-config to boxes-config.new
2. cat fortran.box boxes-config.new > ~/.boxes

... and it's resolved.
