### ISSUE TITLE
Help with updating boxes in Homebrew

### ISSUE THREAD

**Issue by mathomp4** [ascii-boxes/boxes#77]
This is for @tsjensen I guess. I'm [trying to update the boxes version in Homebrew](https://github.com/Homebrew/discussions/discussions/1169), and one of the things that tripped me up was:
```console
❯ brew audit --strict boxes
boxes:
  * Formula boxes contains deprecated SPDX licenses: ["GPL-2.0"].
    You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
    For a list of valid licenses check: https://spdx.org/licenses/
Error: 1 problem in 1 formula detected
```
The reply was:

> Usually, the source headers or the readme files indicate whether it's -only or -or-later. If it's still unclear, you can consult with the developer.

Do you know which is correct? I think it's -only, but I want to be sure!

**Comment by tsjensen** [comment]
That's right, `-only` is the correct one.

However, it's really a bit of a gray area, and I will also not complain if I see `-or-later`.

Thank you for updating *boxes* in Homebrew! 👍

**Comment by mathomp4** [comment]
> That's right, `-only` is the correct one.
> 
> However, it's really a bit of a gray area, and I will also not complain if I see `-or-later`.
> 
> Thank you for updating _boxes_ in Homebrew! 👍

Well, we'll find out if it works. I think I have the new dependencies right!

**Comment by mathomp4** [comment]
Okay. I think I got it working. Hopefully now when the next version (2.1.0?) comes out, I can just use `bump-formula-pr` to get it into homebrew.
