### ISSUE TITLE
Error building v2.1.0 under brew on macOS

### ISSUE THREAD

**Issue by mathomp4** [ascii-boxes/boxes#82]
I seem to be seeing something similar to #80 

I saw it when I tried to update the version in brew: https://github.com/Homebrew/homebrew-core/pull/75486
```
In file included from In file included from ../src/list.c:31:
../src/boxes.c../src/parsing.h:28:10::33:
 fatal error: 'parser.h' file not found
../src/parsing.h:28:10: fatal error: 'parser.h' file not found
#include "parser.h"#include "parser.h"
         ^~~~~~~~~~

         ^~~~~~~~~~
11 error generated.
 error generated.
make[2]: *** [list.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [boxes.o] Error 1
make[1]: *** [build] Error 2
make: *** [build] Error 2
```

I could duplicate that locally, so I closed that PR because it looks like I just can't get v2.1.0 to build. 

I have tried a few things like:
```diff
@@ -15,10 +15,15 @@ class Boxes < Formula

   depends_on "libunistring"
   depends_on "pcre2"
+  depends_on "bison"
+  depends_on "flex"

   def install
+    ENV.deparallelize
+    flex_bin = Formula["flex"].bin/"flex"
+    bison_bin = Formula["bison"].bin/"bison"
     # distro uses /usr/share/boxes change to prefix
-    system "make", "GLOBALCONF=#{share}/boxes-config", "CC=#{ENV.cc}"
+    system "make", "GLOBALCONF=#{share}/boxes-config", "CC=#{ENV.cc}", "LEX=#{flex_bin}", "YACC=#{bison_bin}"
```
So `ENV.deparallelize` is like `make -j1` and I tried fiddling with the build/make to get in `flex` and `bison` which it looks like 2.1.0 uses. But now I seem to be stuck in another set of errors that start like:
```
cpp -I. -I../src -P parser.c parser.p
In file included from parser.c:91:
In file included from ../src/parser.y:27:
In file included from ./boxes.h:33:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:69:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/Availability.h:136:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:142:2: error: #endif without #if
#endif /* #if defined(__has_builtin) */
 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:150:2: error: #endif without #if
#endif /* __ENABLE_LEGACY_IPHONE_AVAILABILITY */
 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:153:32: error: missing '(' after '__has_attribute'
    #if defined(__has_attribute) && defined(__has_feature)
```
This seems very clang-y, but I don't know. I'm attaching the full log in case someone sees something I'm missing.

[01.make.log](https://github.com/ascii-boxes/boxes/files/6372155/01.make.log)

**Comment by mathomp4** [comment]
Now, I did see online somewhere someone saying "use `clang -E` not `cpp`", so I forked boxes, made a wee change:
```diff
diff --git a/src/Makefile b/src/Makefile
index 3f61aa7..a2b8ef9 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -19,6 +19,7 @@


 CC         = gcc
+CPP        = cpp

 OUT_DIR    = ../out
 SRC_DIR    = ../src
@@ -85,7 +86,7 @@ flags_:

 parser.c parser.h: parser.y lex.yy.h | check_dir
        $(YACC) --warnings=all --verbose --defines=parser.h --output=parser.c $<
-       cpp -I. -I$(SRC_DIR) -P parser.c parser.p
+       $(CPP) -I. -I$(SRC_DIR) -P parser.c parser.p

 lex.yy.c lex.yy.h: lexer.l | check_dir
        $(LEX) --header-file=lex.yy.h $<
```
along with passing in `clang -E` as a new `CPP`:
```ruby
    system "make", "GLOBALCONF=#{share}/boxes-config", "CC=#{ENV.cc}", "LEX=#{flex_bin}", "YACC=#{bison_bin}", "CPP=clang -E"
```
but now it's a different error:
```
flex --header-file=lex.yy.h ../src/lexer.l
bison --warnings=all --verbose --defines=parser.h --output=parser.c ../src/parser.y
clang -E -I. -I../src -P parser.c parser.p
clang: error: no such file or directory: 'parser.p'
make[2]: *** [parser.c] Error 1
make[1]: *** [build] Error 2
make: *** [build] Error 2
```
Probably because `clang -E` is not a drop-in replacement for `cpp`.

**Comment by tsjensen** [comment]
Have you tried following the comment in #80? You may also just build the latest master. The key is to have that commit in which declares the build as serial ([patch](https://github.com/ascii-boxes/boxes/commit/d1a1cf158016f24ee9d4785e3e07b82329964d0f.patch)).

**Comment by tsjensen** [comment]
As always, we depend on flex and bison, but only at build time. The runtime does not depend on either.

**Comment by tsjensen** [comment]
The line `cpp -I. -I../src -P parser.c parser.p` can just be removed if it causes problems. It is only there to create some information for troubleshooting. But if it causes problems, kill it.

**Comment by tsjensen** [comment]
I would probably not go down the clang road any further - we don't use it currently, so this is unlikely to be helpful.

**Comment by mathomp4** [comment]
@tsjensen So, some good news. First, I am building off of `master`, essentially, you can see that here:

https://github.com/ascii-boxes/boxes/compare/master...mathomp4:master

If I remove that `cpp` line, it gets further. Huzzah! (I suppose you could do that "if not Darwin").

But now the issue is that it can't seem to find a file:
```console
❯ brew install --build-from-source  boxes
==> Downloading https://github.com/mathomp4/boxes/archive/v2.1.1c.tar.gz
==> Downloading from https://codeload.github.com/mathomp4/boxes/tar.gz/v2.1.1c
######################################################################## 100.0%
==> make GLOBALCONF=/usr/local/Cellar/boxes/2.1.1/share/boxes-config CC=clang LEX=/usr/local/opt/flex/bin/flex YACC=/usr/local/opt/bison/bin
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - src/boxes
```

I *think* it's because you've changed how the make happens. In the formula we have:
```ruby
  def install
    ENV.deparallelize
    flex_bin = Formula["flex"].bin/"flex"
    bison_bin = Formula["bison"].bin/"bison"

    # distro uses /usr/share/boxes change to prefix
    system "make", "GLOBALCONF=#{share}/boxes-config", "CC=#{ENV.cc}", "LEX=#{flex_bin}", "YACC=#{bison_bin}"

    bin.install "src/boxes"
    man1.install "doc/boxes.1"
    share.install "boxes-config"
  end
```
I think the issue might be that `boxes` (the executable) might not be in `src/` anymore, so it's trying to install a non-existent `src/boxes`?

Do you know what those last three lines should be now?

**Comment by tsjensen** [comment]
That's great progress! 😎👍

The executable is now created in `out/` instead of `src/`.

You're close!

**Comment by tsjensen** [comment]
> If I remove that cpp line, it gets further. Huzzah! (I suppose you could do that "if not Darwin").

Removed the `cpp` invocation for pre-processor debugging. ✔️

**Comment by mathomp4** [comment]
@tsjensen Thanks. I'll give it a try tonight. Well, after I go look up the whole "resync a fork" thing. Or...wait, I think I can have `brew` take the head of a repo. Hmm. Learning!

**Comment by mathomp4** [comment]
Looks good!
```console
❯ brew install --build-from-source --HEAD  boxes
==> Cloning https://github.com/ascii-boxes/boxes.git
Updating /Users/fortran/Library/Caches/Homebrew/boxes--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 4daa0f4 Fix repo encoding of ISO-8859-15 encoded files #83
==> make GLOBALCONF=/usr/local/Cellar/boxes/HEAD-4daa0f4/share/boxes-config CC=clang LEX=/usr/local/opt/flex/bin/flex YACC=/usr/local/opt/bison
🍺  /usr/local/Cellar/boxes/HEAD-4daa0f4: 7 files, 218.2KB, built in 9 seconds
❯ boxes -version
boxes version 2.1.0 (4daa0f4)
```

And I can do aliases and all that as well! 

Once 2.1.1 or 2.2.0 or whatever is released, I'll work on getting a new update to brew!

**Comment by tsjensen** [comment]
Fantastic! Thank you for your support, @mathomp4 ⭐
