### ISSUE TITLE
Geany integration

### ISSUE THREAD

**Issue by Davidy22** [ascii-boxes/boxes#85]
The integrations page said to drop something by here if I knew another editor you can integrate boxes into so here's my screenshot for [geany](https://geany.org/)

In the top menu, go to Edit -> Format -> Send selection to -> Set custom commands and you'll get a window that looks like this:

![Screenshot from 2021-08-12 18-08-20](https://user-images.githubusercontent.com/872968/129179551-eeb18a99-1f08-4de6-b9f7-2cd37bc994c0.png)

Click add and it'll add a new command slot. You type a shell command in the command field and when you hit CTRL + number it's like you did an `echo | [command that you typed]`. In the above screenshot, I just typed boxes, so it'll pipe my text through default boxes.

![Screenshot from 2021-08-12 18-15-29](https://user-images.githubusercontent.com/872968/129180331-58be3ba9-5b70-4365-8922-badacb14360c.png)
![Screenshot from 2021-08-12 18-15-41](https://user-images.githubusercontent.com/872968/129180335-30a76994-67ab-47c8-9b14-b42b971e7094.png)

**Comment by tsjensen** [comment]
Thanks for the info! First time I heard of Geany. 😊

You can open a PR against the `gh-pages` branch for this information. [Here](https://boxes.thomasjensen.com/2021/05/website-updates.html#website-on-local-machine)'s how to set everything up on your local machine.

Else, I can add it to the website for you, which will just take a little time 🐌

**Comment by Davidy22** [comment]
just made a quick post here to raise this, can take a look but might be a minute for me too.

**Comment by tsjensen** [comment]
No worries! I'm just asking what you want to do.  
When you create the page, you'd be listed in our Git repository, and I save a little bit of work, is all. Whatever you prefer! 😄

**Comment by tsjensen** [comment]
Thanks for the PR! Just merged it. 👍
