### ISSUE TITLE
Update (Ubuntu) Packages to v2

### ISSUE THREAD

**Issue by macwinnie** [ascii-boxes/boxes#95]
Hi,

giving the Ubuntu documentation a look, also the next release (Ubuntu 22.04) in next April is planned to be released with boxes 1.3 as latest package provided through their package management.

http://manpages.ubuntu.com/manpages/jammy/man1/boxes.1.html

Is there a roadmap, when the v2 will be “official” and not only installable through the source code?

(The cause of my question is the problem with UTF-8 strings – using german letters like “ä“, “ö“, “ü“ or even hypens like “–“ cause the boxes to count byte-size instead of string-length with v1.3 what causes the boxes to look broken – and I hope that this problem would be fixed by the `-n` attribute in v2 =D )

Thanks a lot!
Best
Martin

**Comment by tsjensen** [comment]
Afaik, *boxes* is packaged for Debian, which propagates to Ubuntu.  
I missed the code freeze for Debian bullseye by a few days unfortunately, so boxes v2 will officially be only in bookworm.

@carnil is maintaining the Debian packages for us, and he hinted that he might make them available on experimental so that we can get boxes v2 before bookworm. @carnil, it would be great if you could drop a line here when things happen so that people know. Thank you!

**Comment by carnil** [comment]
@tsjensen yes I got a bit backlogged on updating to v2 for Debian, will do and try to not forget to ping here when done. Thanks for the reminder!

**Comment by carnil** [comment]
@tsjensen I uploaded boxes/2.1.1-1 to Debian unstable (https://tracker.debian.org/news/1285920/accepted-boxes-211-1-source-into-unstable/) and so if no issues arise will migrate to testing/bookworm soon. That is Ubuntu can sync it for their next release (Ubuntu 22.04).

@tsjensen in same way, if you have any improvement you see needed in the Debian package let me know. At some point I want to as well address the failing https://salsa.debian.org/carnil/boxes/-/jobs/2269686 and the missing hardening (bindnow).

**Comment by tsjensen** [comment]
Thanks @carnil for the quick response!

> if you have any improvement you see needed in the Debian package let me know

Nothing much, I just noticed [here](https://salsa.debian.org/carnil/boxes/-/blob/aab3bc52058d4bf9a84adf7b7ccabf2efac2ece1/debian/copyright) (is that the right place?) that the copyright line is a bit outdated. The current copyright line is

    Copyright (c) 1999-2021 Thomas Jensen and the boxes contributors

And also, the license should be `GPL-2` instead of `GPL-2+`. This is not mission critical though.

Optionally, you might want to pull [this commit](https://github.com/ascii-boxes/boxes/commit/4fc33e7cee5860a482338389c91548e776de2d24) ("Fix quoting of closing comment tags in config") which I really should have released as a patch version already.

**Comment by carnil** [comment]
> Thanks @carnil for the quick response!
> 
> > if you have any improvement you see needed in the Debian package let me know
> 
> Nothing much, I just noticed [here](https://salsa.debian.org/carnil/boxes/-/blob/aab3bc52058d4bf9a84adf7b7ccabf2efac2ece1/debian/copyright) (is that the right place?) that the copyright line (line 7) is a bit outdated. The current copyright line is
> 
> ```
> Copyright (c) 1999-2021 Thomas Jensen and the boxes contributors
> ```

Alright, I should fix that.

> And also, the license should be `GPL-2` instead of `GPL-2+`. This is not mission critical though.

Seems I missed the changes in 7d982275830e91b904b46dd3f1c246d5eefa2a11 . But I need to recheck if parts (formerly the emacs integration was GPL-2+ at least) if there are other wrong parts.

> Optionally, you might want to pull [this commit](https://github.com/ascii-boxes/boxes/commit/4fc33e7cee5860a482338389c91548e776de2d24) ("Fix quoting of closing comment tags in config") which I really should have released as a patch version already.

Thanks will try to cherry-pick as well in the next upload.

**Comment by tsjensen** [comment]
> > And also, the license should be GPL-2 instead of GPL-2+. This is not mission critical though.
> 
> Seems I missed the changes in [7d98227](https://github.com/ascii-boxes/boxes/commit/7d982275830e91b904b46dd3f1c246d5eefa2a11). But I need to recheck if parts (formerly the emacs integration was GPL-2+ at least) if there are other wrong parts.

Yea, we are not super clean on this, but GPL-2.0-only was the license I had always intended. I have an internal task to clean that up. Until I actually do that, it's okay to list *boxes* as GPL-2.0-or-later, too.

**Comment by tsjensen** [comment]
Hi @carnil - how are things going? Is there anything we can do to help?

**Comment by carnil** [comment]
> Hi @carnil - how are things going? Is there anything we can do to help?

@tsjensen: do you mean about the copyright correction in `debian/copyright`? Given your statement in  https://github.com/ascii-boxes/boxes/issues/95#issuecomment-991892829 I was assuming it is okay to defer the changes once they are cleaned up on upstream and then sync the change as well in Debian. Or is it about something else yet?

**Comment by tsjensen** [comment]
@carnil Sorry, I should have properly read all the comments before asking again. As I understand them, boxes v2 is already available in bullseye/unstable, and will be in bookworm. So there is currently nothing to do! ([Here](https://serverfault.com/q/22414/191662)'s instructions on how to install the packages from unstable.)

You are right that my remarks above were all non-critical, and we can let them sit for a while. I made a note for myself to let you know once the license stuff is cleaned up.

**Comment by carnil** [comment]
> @carnil Sorry, I should have properly read all the comments before asking again. As I understand them, boxes v2 is already available in bullseye/unstable, and will be in bookworm. So there is currently nothing to do! ([Here](https://serverfault.com/q/22414/191662)'s instructions on how to install the packages from unstable.)
> 
> You are right that my remarks above were all non-critical, and we can let them sit for a while. I made a note for myself to let you know once the license stuff is cleaned up.

@tsjensen no worries and thanks! I just wanted to make sure I did not oversee something. Yes boxes 2.1.1 (or later) will be in bookworm (modulo if some release critical issue would appear which make it need to be removed from testing).

**Comment by tsjensen** [comment]
@carnil Licenses have been cleaned up (#101). This will only affect the next release (currently not planned).

**Comment by tsjensen** [comment]
We just released [v2.2.0](https://github.com/ascii-boxes/boxes/releases/tag/v2.2.0), so there is now a proper release with the upgraded license.

**Comment by carnil** [comment]
> We just released [v2.2.0](https://github.com/ascii-boxes/boxes/releases/tag/v2.2.0), so there is now a proper release with the upgraded license.

@tsjensen Thank you! I uploaded the new upstream version to Debian unstable.

**Comment by tsjensen** [comment]
I just tried an `apt-get install -y boxes` in a clean ubuntu:latest, and got *boxes* v2.1.1.

So I think we have v2 support for Ubuntu now. Thanks @carnil for staying on top of this! ⭐
