### ISSUE TITLE
Question/Clarification on License (GPL-2 vs. GPL-2+)

### ISSUE THREAD

**Issue by carnil** [ascii-boxes/boxes#97]
Hi

As raised in https://github.com/ascii-boxes/boxes/issues/95 I would like to rectify the `debian/copyright` information in the Debian package downstream.

In https://github.com/ascii-boxes/boxes/commit/7d982275830e91b904b46dd3f1c246d5eefa2a11 the license was changed to plain GPLv2. But the https://github.com/ascii-boxes/boxes/blob/master/LICENSE still contains the original commit, and referring to the GPL-2+ version, with the "or (at your option) any later version." clause.

Is the later a leftover and should the project be considered GPL-2 only (apart the `doc/boxes.el` which is still GPL-2+ and the embedded `src/misc/getopt.{c,h}`?

Thanks for the potential clarification!

Regards

**Comment by carnil** [comment]
Nevermind, I think this was just a shortcut question, and the status is clear enough and correct.

**Comment by tsjensen** [comment]
Ha, my [comment in #95](https://github.com/ascii-boxes/boxes/issues/95#issuecomment-991892829) would have fit here better. 😄
