### ISSUE TITLE
Spacing for Unicode Block characters is off

### ISSUE THREAD

**Issue by nnuel** [ascii-boxes/boxes#98]
Spacing for Unicode Block characters is off

Input

SHAPES {   
nw ("██") n ("█") ne ("██")   
 w ("██")          e ("██")   
sw ("██") s ("█") se ("██")   
}   

My font has widthxheight ratio of 1x2, so I'd need to block character for a square block.

The output is:

```
echo "boxes" | boxes
███████
██         ██
██  boxes  ██
██         ██
███████
```

This is on Linux in the `foot` terminal, with `fish` shell. But it occurs similarly in other terminals and shells.
Boxes 2.1.1

In foot/fish
![image](https://user-images.githubusercontent.com/4148154/154793344-3795c914-2140-4ce9-beb7-bfc82905e56b.png)

In kitty/bash
![image](https://user-images.githubusercontent.com/4148154/154793375-3e74916c-d3de-4024-9032-16c4f18ebd75.png)

It must be something with unicode-encoding and spaces and tabs, but I can't seem to get it working. I really like the idea of this program, so I'd like to help out to get it working, but this is as far as I could get on my own.

**Comment by nnuel** [comment]
if I double the characters in N and S, then it would just push the East border even further:

![image](https://user-images.githubusercontent.com/4148154/154793485-04032ecb-339e-4c8d-8a7f-2b82b0103d53.png)

**Comment by tsjensen** [comment]
Right, the config file is currently ASCII. We aim to change this, but it's a lot of work, see #72.

**Comment by tsjensen** [comment]
FYI, these kinds of boxes are now supported, if you use boxes [v2.3.0](https://github.com/ascii-boxes/boxes/releases/tag/v2.3.0) or newer. 😄
